---
title: "Storyboard Visualization"
author: "Jonah Klein-Collins"
date: "2022-11-28"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

```{r}
library(tidyverse)
library(ggplot2)
```
# Import Files
```{r}
touches <- read_csv("C:/Users/jonah/OneDrive/Documents/Comp_Stat_112/Project/touches.csv")
passes <- read_csv("C:/Users/jonah/OneDrive/Documents/Comp_Stat_112/Project/passes.csv")
drives <- read_csv("C:/Users/jonah/OneDrive/Documents/Comp_Stat_112/Project/drives.csv")
p_r_handler <- read_csv("C:/Users/jonah/OneDrive/Documents/Comp_Stat_112/Project/p_r_handler.csv")
p_r_roller <- read_csv("C:/Users/jonah/OneDrive/Documents/Comp_Stat_112/Project/p_r_roller.csv")
hustle <- read_csv("C:/Users/jonah/OneDrive/Documents/Comp_Stat_112/Project/hustle.csv")
transitions <- read_csv("C:/Users/jonah/OneDrive/Documents/Comp_Stat_112/Project/transitions.csv")

playoff_status = tibble(
  Team = c("Atlanta Hawks" , "Boston Celtics"       
, "Brooklyn Nets"        ,  "Charlotte Hornets"     
 ,"Chicago Bulls"         , "Cleveland Cavaliers"   
 , "Dallas Mavericks"     ,  "Denver Nuggets"        
 , "Detroit Pistons"      ,  "Golden State Warriors" 
, "Houston Rockets"       , "Indiana Pacers"        
, "LA Clippers"           , "Los Angeles Lakers"    
, "Memphis Grizzlies"     , "Miami Heat"            
, "Milwaukee Bucks"       , "Minnesota Timberwolves"
, "New Orleans Pelicans"  , "New York Knicks"       
, "Oklahoma City Thunder" , "Orlando Magic"         
, "Philadelphia 76ers"     ,"Phoenix Suns"          
, "Portland Trail Blazers", "Sacramento Kings"      
, "San Antonio Spurs"     , "Toronto Raptors"       
, "Utah Jazz"    ,          "Washington Wizards"),

Playoffs = c("Play-in Team", "Playoff Team", 
             "Play-in Team", "Play-in Team", 
             "Playoff Team", "Play-in Team", 
             "Playoff Team", "Playoff Team", 
             "No Playoffs", "Playoff Team", 
             "No Playoffs", "No Playoffs", 
             "Play-in Team", "No Playoffs", 
             "Playoff Team", "Playoff Team", 
             "Playoff Team", "Play-in Team", 
             "Play-in Team", "No Playoffs", 
             "No Playoffs", "No Playoffs", 
             "Playoff Team", "Playoff Team", 
             "No Playoffs", "No Playoffs", 
             "Play-in Team", "Playoff Team", 
             "Playoff Team", "No Playoffs")
)
teams1 <- p_r_handler[1]
teams2 <- playoff_status[1]

pass_touch <- passes %>% 
  left_join(touches) %>% 
  left_join(playoff_status) %>% 
  rename("Wins" = "W")

paint_drive <- drives %>% 
  left_join(touches) %>% 
  inner_join(playoff_status) %>% 
  rename("Wins" = "W")
```
# Visualizations
```{r, echo = FALSE}
drives %>% 
  left_join(playoff_status) %>% 
  rename("Wins" = "W") %>% 
  ggplot(aes(x = `DRIVES`, y = Playoffs, fill = Playoffs))+
  geom_boxplot()+
  scale_fill_manual(values = c("brown", "darkgoldenrod2", "chartreuse4"))+
  theme_classic()+
  geom_abline(slope = -.03, intercept = .374, alpha = .2 )+
  labs(y = "Playoff Status", x = "Drives (per Game)", title = "NBA Drive Frequencies and Playoff Status")

p_r_handler %>% 
  left_join(playoff_status, by = c("TEAM" = "Team")) %>% 
  ggplot(aes(x = `FREQ%`, y = PPP, color = Playoffs))+
  geom_text(aes(label = TEAM), size = 3)+
  scale_color_manual(values = c("brown", "darkgoldenrod2", "chartreuse4"))+
  theme_classic()

pass_touch %>% 
  ggplot(aes(x = SecondaryAST, y = `PTS PerTouch`, color = Playoffs))+
  geom_text(aes(label = Team), size = 1.7)+
  scale_color_manual(values = c("brown", "darkgoldenrod2", "chartreuse4"))+
  theme_classic()+
  geom_abline(slope = -.03, intercept = .374, alpha = .2 )+
  annotate(geom = "text", x = 4.5, y =.245, label = "Cutoff Line", size = 2, alpha = .2)+
  xlim(2, 5)+
  labs(y = "Points per Touch", x = "Secondary Assists (per Game)", title = "NBA Passing Styles and Playoff Qualification Status")

pass_touch %>% 
  ggplot(aes(x = SecondaryAST, y = `PTS PerTouch`, color = Playoffs))+
  geom_point(size = 3)+
  scale_color_manual(values = c("brown", "darkgoldenrod2", "chartreuse4"))+
  theme_classic()+
  geom_abline(slope = -.03, intercept = .374, alpha = .2 )+
  annotate(geom = "text", x = 4.5, y =.245, label = "Cutoff Line", size = 2, alpha = .2)+
  xlim(2, 5)+
  labs(y = "Points per Touch", x = "Secondary Assists (per Game)", title = "NBA Passing Styles and Playoff Qualification Status")

transitions %>% 
  left_join(playoff_status, by = c("TEAM" = "Team")) %>% 
  left_join(touches[,1:3]) %>% 
  ggplot(aes(x = `FREQ%`, y = PPP, color = Playoffs))+
  geom_point(size = 3)+
  scale_color_manual(values = c("brown", "darkgoldenrod2", "chartreuse4"))+
  theme_classic()+
  geom_hline(yintercept = 1.135, alpha = .2)+
  annotate(geom = "text", x = 17.5, y = 1.138, label = "Cutoff Line", size = 2, alpha = .2)
  labs(y = "Points Per Play", x = "Transition Frequency", title = "Transition Frequency, Efficiency, and Playoff Status")

```
```{r}
write_csv(playoff_status, file = "playoff_status.csv")
```

